from enum import Enum


class Role(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    RESTAURANT_OWNER = "RESTAURANT_OWNER"
    RESTAURANT_STAFF = "RESTAURANT_STAFF"
    CUSTOMER = "CUSTOMER"
    DELIVERY_PARTNER = "DELIVERY_PARTNER"
