-- Create schemas for each bounded context (schema-per-module strategy)

CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS restaurants;
CREATE SCHEMA IF NOT EXISTS menus;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS payments;
CREATE SCHEMA IF NOT EXISTS deliveries;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS reviews;
CREATE SCHEMA IF NOT EXISTS promotions;
CREATE SCHEMA IF NOT EXISTS analytics;

-- Grant usage to application roles
GRANT USAGE ON SCHEMA identity TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA users TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA restaurants TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA menus TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA orders TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA payments TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA deliveries TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA notifications TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA reviews TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA promotions TO app_tenant_scoped, app_admin;
GRANT USAGE ON SCHEMA analytics TO app_tenant_scoped, app_admin;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA restaurants GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA menus GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA deliveries GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA reviews GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA promotions GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant_scoped;

ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA users GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA restaurants GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA menus GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA orders GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA payments GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA deliveries GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA notifications GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA reviews GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA promotions GRANT ALL PRIVILEGES ON TABLES TO app_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT ALL PRIVILEGES ON TABLES TO app_admin;
