from enum import StrEnum


class DeliveryStatus(StrEnum):
    PENDING_ASSIGNMENT = "PENDING_ASSIGNMENT"
    ASSIGNED = "ASSIGNED"
    PARTNER_EN_ROUTE_TO_PICKUP = "PARTNER_EN_ROUTE_TO_PICKUP"
    AT_PICKUP = "AT_PICKUP"
    EN_ROUTE_TO_DELIVERY = "EN_ROUTE_TO_DELIVERY"
    AT_DELIVERY = "AT_DELIVERY"
    DELIVERED = "DELIVERED"
    NO_PARTNER_AVAILABLE = "NO_PARTNER_AVAILABLE"
    REASSIGNED = "REASSIGNED"
