from enum import StrEnum


class MetricType(StrEnum):
    ORDER_COUNT = "ORDER_COUNT"
    REVENUE = "REVENUE"
    AVERAGE_ORDER_VALUE = "AVERAGE_ORDER_VALUE"
    AVERAGE_DELIVERY_TIME = "AVERAGE_DELIVERY_TIME"
    CUSTOMER_COUNT = "CUSTOMER_COUNT"
    POPULAR_ITEMS = "POPULAR_ITEMS"
    PEAK_HOURS = "PEAK_HOURS"
